### ISSUE TITLE
Error TS2307

### ISSUE THREAD

**Issue by Hwiet** [sinisimattia/tapi#18]
**Describe the bug**
When building the project after installing tapi, get several TS2307 errors (e.g. `Error: node_modules/tapi.js/dist/es/index.d.ts:1:21 - error TS2307: Cannot find module '@/core/Builder' or its corresponding type declarations`).

May or may not be relevant, I got this error on an Angular 15 project.

**To Reproduce**
Install library using `npm i -D tapi.js`, then build/run the project (e.g. `ng serve` on Angular)

**Expected behavior**
Successful compilation

**Environment (please complete the following information):**
 - tapi version 0.5.0
 - node version 9.5.0
 - Angular version 15.2.0

**Typescript config file(s):**
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "ES2022",
    "module": "ES2022",
    "useDefineForClassFields": false,
    "lib": [
      "ES2022",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
}
```

**Additional context**
I assume there is some (Babel?) syntax that is not supported universally in JavaScript. I could probably do a few searches to find how to compile with this syntax but put up this issue since other new users may encounter this issue.

**Comment by sinisimattia** [comment]
Thanks a lot for creating this issue. I'll take a look as soon as I can and put out a fix for it

**Comment by sinisimattia** [comment]
@Hwiet A PR for this issue has been linked, more testing to come. Could you try installing from this branch to see if it also works for you?
