### ISSUE TITLE
Wrong behavior with inheritance?

### ISSUE THREAD

**Issue by Gregory-Gerard** [sinisimattia/tapi#4]
**Describe the bug**
I'm currently working with tapi.js to parse API response and create new class instance with ease 🙂

However, when I use tapi with classes that extend an abstract class, the class returned by the builder is the abstract class and not the concrete class.

**To Reproduce**
https://stackblitz.com/edit/typescript-t4ibg5?devToolsHeight=33&file=index.ts

**Expected behavior**
I'd expect that builder return concrete class instance.

**Environment (please complete the following information):**
 - tapi version v0.4.2
- node version v18.9.0

**Typescript config file(s):**
```json
{
  "compilerOptions": {
    "target": "ESNext",
    "useDefineForClassFields": true,
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "allowJs": false,
    "skipLibCheck": true,
    "esModuleInterop": false,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "experimentalDecorators": true
  },
  "include": ["src"],
  "references": [{ "path": "./tsconfig.node.json" }]
}
```

```json
{
  "compilerOptions": {
    "composite": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "allowSyntheticDefaultImports": true
  },
  "include": ["vite.config.ts"]
}
```

**Additional context**
I have a little trouble with prototype inheritance in JS, but from what I understand :

When I call `Object.getPrototypeOf(Admin)`, the prototype of `UserObject` is returned.

So in the `BuildableResource.ts` file, when tapi gets the constructor like this: `Admin.constructor.prototype.constructor`, this is where the `UserObject` is returned.

I'm actively looking for a solution and will come back to post it if I find one, but in the meantime I'm posting the issue because the problem might be with my class definitions? In any case several pairs of eyes are better than one 😅

Thanks!

**Comment by Gregory-Gerard** [comment]
Mh, the problem has nothing to do with the inheritance of prototypes.

The real problem is with the decorators and builder, which are instantiated on the abstract class, these decorators (Transform for example) will instantiate a new builder (via `get build()` in src/contracts/BuildableResource.ts:23).

So, the builder already instantiated at the class level, it will be reused (see src/contracts/BuildableResource.ts:26)

See my new example which illustrates all this, with one class having decorators and another without decorators : https://stackblitz.com/edit/typescript-heo41a?devToolsHeight=33&file=index.ts

There are several solutions:
- Use decorators at the concrete class level so that the builder is still attached to the concrete class, but the abstract class will no longer have any use.
- Update the `baseObject` of the builder at each `get build()` to be sure to build on the current class? I'm not sure of the performance impact.

I am of course open to help, waiting for your opinion on the different solutions and on the problem 👋

**Comment by sinisimattia** [comment]
@Gregory-Gerard Thanks for reporting this, I'm of course inclined to proceed with the second solution, I'll attempt a fix that doesn't slow things down and, if I manage to do it, I'll tag you in the PR. Feel free to do the same

**Comment by sinisimattia** [comment]
I'll also try to reproduce this in a unit test so that it doesn't happen in the future

**Comment by Gregory-Gerard** [comment]
@sinisimattia Nice! Thanks.

What about instantiating Builder in `Properties.Resource` decorator?

And applying this decorator on concrete class instead of abstract class. This fix would be lightweight I think and few / no side effect.

I will do a PR tonight if this solution is good for you 😉

**Comment by sinisimattia** [comment]
Yes, if you do please include a unit test. If I merge I'll do the same.
Oh and thanks again @Gregory-Gerard!

**Comment by sinisimattia** [comment]
@Gregory-Gerard I have fixed the issue, it was in the BuildableResource class itself. I'll add you as a reviewer to my PR

**Comment by sinisimattia** [comment]
Ok here's the pull request, feel free to look around. If everything works out I'll create a new release

**Comment by Gregory-Gerard** [comment]
> Ok here's the pull request, feel free to look around. If everything works out I'll create a new release

Great, I had started working on it and came up with a similar solution, so it looks good to me 👍

If it's ok with you, when I get home from work, I'll install the PR branch locally and test it on my project (which goes a bit further with inheritance than my examples so it will be a good test). Anyway, thanks for your work! 😁

**Comment by sinisimattia** [comment]
No problem, If you want to write a more thorough unit test please be my guest. Thanks for the cooperation man!

**Comment by Gregory-Gerard** [comment]
@sinisimattia That's almost right, inheritance works correctly, but when you instantiate a new builder, you lose all the decorators, so the transformers for example are not applied anymore 🥲

If you add `expect(instance.name).toStrictEqual('THIS IS MY NAME')` to `when using the decorators.` test in `tests\Inheritance.test.ts`, you will see that the transformation is not applied.

I'm working on a fix, either we update base object on already instantiated builder, either we clone builder with new base object.

Maybe something like this (if base object is public of course, or with a setter?)
```typescript
if (this.builder && !this.builder.isUsingClass(c)) {
	this.builder.baseObject = new c();
} else if (!this.builder) {
	this.builder = new Builder<this>(c);
}
```

What do you think? With this snippet, all tests are green 😄 I could submit this snippet on top of your PR + some unit test, testing transformers and so on.

**Comment by sinisimattia** [comment]
Yes this works for me as well! Nice catch :+1:

**Comment by Gregory-Gerard** [comment]
> Yes this works for me as well! Nice catch 👍

Work done! You can check my PR which is some additional fixes on top of your PR : https://github.com/sinisimattia/tapi/pull/6

Thanks!
